### ISSUE TITLE
Vector data type implementation

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AP-CoreTypes#8]
See https://www.autosar.org/fileadmin/user_upload/standards/adaptive/19-11/AUTOSAR_SWS_CoreTypes.pdf for requirements to cover.

**Comment by bburda** [comment]
Requirements to cover:
[SWS_CORE_01301]
[SWS_CORE_01390]
[SWS_CORE_01391]
[SWS_CORE_01392]
[SWS_CORE_01393]
[SWS_CORE_01394]
[SWS_CORE_01395]
[SWS_CORE_01396]

**Comment by splywaczyk** [comment]
Hi,
I'd like to implement #39 (ara::core::Vector) but have doubts regarding to

> SWS_CORE_01301
> All members of this class shall behave identical to those of std::vector from [5] section 23.3.6, except that the default value for the Allocator template argument is implementation-defined.

How do you guys understand the last part? Should I implement a new allocator and pass it as a default one for `ara::core::Vector`? Why `std::allocator` cannot be used?
